name: cycle-life
channels:
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2019.1.23
  - certifi=2019.3.9
  - cycler=0.10.0
  - freetype=2.9.1
  - h5py=2.9.0
  - hdf5=1.10.4
  - icu=58.2
  - intel-openmp=2019.3
  - joblib=0.13.2
  - jpeg=9b
  - kiwisolver=1.1.0
  - libpng=1.6.37
  - matplotlib=3.0.3
  - mkl=2019.3
  - mkl_fft=1.0.12
  - mkl_random=1.0.2
  - numpy=1.16.3
  - numpy-base=1.16.3
  - openssl=1.1.1b
  - pandas=0.24.2
  - pip=19.1.1
  - pyparsing=2.4.0
  - pyqt=5.9.2
  - python=3.7.3
  - python-dateutil=2.8.0
  - pytz=2019.1
  - qt=5.9.7
  - scikit-learn=0.21.1
  - scipy=1.2.1
  - setuptools=41.0.1
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.28.0
  - wheel=0.33.4
  - zlib=1.2.11
  - pip:
    - altair==3.0.1
    - attrs==19.1.0
    - backcall==0.1.0
    - bleach==3.1.0
    - colorama==0.4.1
    - decorator==4.4.0
    - defusedxml==0.6.0
    - entrypoints==0.3
    - ipykernel==5.1.1
    - ipython==7.5.0
    - ipython-genutils==0.2.0
    - jedi==0.13.3
    - jinja2==2.10.1
    - jsonschema==3.0.1
    - jupyter-client==5.2.4
    - jupyter-core==4.4.0
    - jupyterlab==1.0.0a3
    - jupyterlab-server==0.3.0
    - markupsafe==1.1.1
    - mistune==0.8.4
    - nbconvert==5.5.0
    - nbformat==4.4.0
    - notebook==5.7.8
    - pandocfilters==1.4.2
    - parso==0.4.0
    - pickleshare==0.7.5
    - prometheus-client==0.6.0
    - prompt-toolkit==2.0.9
    - pygments==2.4.1
    - pyrsistent==0.15.2
    - pywinpty==0.5.5
    - pyzmq==18.0.1
    - send2trash==1.5.0
    - terminado==0.8.2
    - testpath==0.4.2
    - toolz==0.9.0
    - tornado==5.1.1
    - traitlets==4.3.2
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - xlrd==1.2.0

